patchedDependencies:
  nimiq-rpc-client-ts@1.0.0-beta.38: patches/nimiq-rpc-client-ts@1.0.0-beta.38.patch
ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - bufferutil
  - es5-ext
  - esbuild
  - sharp
  - simple-git-hooks
  - utf-8-validate
  - vue-demi
  - workerd
