packages:
  - ./
patchedDependencies:
  nimiq-rpc-client-ts@1.0.0-beta.38: patches/nimiq-rpc-client-ts@1.0.0-beta.38.patch
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
  - vue-demi
