packages:
  - ./
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
  - vue-demi
patchedDependencies:
  '@nimiq/core': patches/@nimiq__core.patch
shellEmulator: true
trustPolicy: no-downgrade
